### ISSUE TITLE
Static URL REACT_APP_BACKEND

### ISSUE THREAD

**Issue by nutansonale** [PatrickHallek/automated-irrigation-system#16]
when i start a docker-compose services, it gets its own DNS and set of IP will be configured to all containers. I found that the **REACT_APP_BACKEND_URL** variable is referring to a static IP address **"192.168.178.50"**  while node container has got different IP. 
can you explain why this particular IP address is chosen ?

**Linechart.js** uses the host rpi IP address  to fetch data from the node container.
you may have to name the container using "container_name" in docker-compose.yml

also while get calls are made to the node container through the host raspberry-pi IP means if my pi has "192.168.178.51" the call will be made to "http://192.168.178.51:5000/undefined/measurements/day/..." 
is it not simple to connect the two containers by giving some name?
as they will be in same network they can ping using these names as the DNS in docker will take care of that.

**Comment by PatrickHallek** [comment]
If I understand your question correct, you are not aware that the frontend is running as client in your browser. The client is therefore not on the same machine as the backend. Of course you are requesting the frontend code from the raspberry pi (198.168.178.51:5000), but the api calls are executed through your local client (eg. chrome on your mobile phone). You can’t excess the Docker container through another machine with the container address. So you need to excess the backend APIs through the raspberry IP with the mapped container port (198.168.178.51:3000/....). For example the backend and mongodb are connected through the container address, because the backend code gets executed directly on the raspberry itself and not from another location.

**Comment by nutansonale** [comment]
thank you for clarifying this to me.
